
# Paths
EXPERIMENT_SAVE_DIR: "experiments"

# Data
TEST_DATA: {
  PATH: "data/temp/test_data.hdf5",
  SCALE: 4,
  SEQ_LEN: 5,
  NUM_CHANNELS: 1,
  HR_PATCH_SHAPE: [32, 32]
}

BATCH_SIZE: 15
TRAIN_VALID_SPLIT: 0.1

# Training
CHECKPOINT_VALID_EVERY_N_EPOCH: 2