
# Paths
EXPERIMENT_SAVE_DIR: "experiments"

# General
SCALE: 4

# Data
SEQ_LEN: 5
NUM_CHANNELS: 1
HR_PATCH_SHAPE: [36, 36]

DATA: {
  TEST_DATA: "data/temp/test_data.hdf5"
}

BATCH_SIZE: 15
TRAIN_VALID_SPLIT: 0.1

# Training
CHECKPOINT_VALID_EVERY_N_EPOCH: 2