
# Paths
EXPERIMENT_SAVE_DIR: "experiments"

# Data
TEST_DATA: {
  PATH: "data/temp/test_data.hdf5",
  SCALE: 4,
  SEQ_LEN: 5,
  NUM_CHANNELS: 1,
  HR_PATCH_SHAPE: [32, 32],
  HAS_COLOR_CHANNEL: False
}

MYAMAR_DATA: {
  PATH: "/home/xijun/sony/train_u4_no_mc_filtered.hdf5",
  SCALE: 4,
  SEQ_LEN: 5,
  NUM_CHANNELS: 1,
  HR_PATCH_SHAPE: [32, 32],
  HAS_COLOR_CHANNEL: False
}

VIMEO_SAMPLE_DATA: {
  #PATH: "../data/vimeo/processed/vimeo_subset_v3.h5",
  PATH: "data/temp/vimeo_subset_v7.h5",
  SCALE: 4,
  SEQ_LEN: 7,
  NUM_CHANNELS: 3,
  HR_PATCH_SHAPE: [32, 32],
  HAS_COLOR_CHANNEL: True
}

BATCH_SIZE: 32
TRAIN_VALID_SPLIT: 0.1

# Training
CHECKPOINT_VALID_EVERY_N_EPOCH: 2