## NOTE: DONT CHANGE ANY OLD SETTINGS - WILL CAUSE MODEL LOAD ISSUE FOR OLD MODELS

###### VSRTE1 ######
# Sample
VSRTE1_SAMPLE: {embed_dim: 4, n_heads: 4, n_transformerhidden: 4, n_transformerlayers: 2, n_Convhidden: 20, n_Convlayers: 2, n_stride: 2, dropout: 0.5}

# 2.6 M params
VSRTE1_1: {embed_dim: 128, n_heads: 8, n_transformerhidden: 128, n_transformerlayers: 2, n_Convhidden: 128, n_Convlayers: 8, n_stride: 2, dropout: 0.2}

# 500K params - Larger transform, smaller conv
VSRTE1_2: {embed_dim: 64, n_heads: 4, n_transformerhidden: 64, n_transformerlayers: 6, n_Convhidden: 64, n_Convlayers: 4, n_stride: 2, dropout: 0.2}

# 500K params - Larger conv, smaller transform
VSRTE1_3: {embed_dim: 64, n_heads: 4, n_transformerhidden: 64, n_transformerlayers: 2, n_Convhidden: 64, n_Convlayers: 8, n_stride: 2, dropout: 0.2}

# 500K params - Larger conv, smaller transform
VSRTE1_4: {embed_dim: 64, n_heads: 4, n_transformerhidden: 32, n_transformerlayers: 2, n_Convhidden: 32, n_Convlayers: 4, n_stride: 2, dropout: 0.2}

###### VSRTE2 ######

# 800K params
VSRTE2_1: {embed_dim: 128, n_heads: 4, n_transformerhidden: 64, n_transformerlayers: 5, n_Convhidden: 32, n_Convlayers: 4, n_stride: 2, dropout: 0.2}

# 2.2M params
VSRTE2_2: {embed_dim: 256, n_heads: 4, n_transformerhidden: 256, n_transformerlayers: 4, n_Convhidden: 32, n_Convlayers: 4, n_stride: 2, dropout: 0.2}


###### VSRTP1 ######
# 700K params
VSRTP1_1: {embed_dim: 8, n_heads: 4, n_transformerhidden: 256, n_transformerlayers: 6, n_Convhidden: 8, n_Convlayers: 1, n_stride: 2, dropout: 0.2}

# 2.2M params
VSRTP1_2: {embed_dim: 24, n_heads: 4, n_transformerhidden: 256, n_transformerlayers: 6, n_Convhidden: 64, n_Convlayers: 1, n_stride: 2, dropout: 0.2}

# 1.3M params
VSRTP1_3: {embed_dim: 16, n_heads: 4, n_transformerhidden: 128, n_transformerlayers: 3, n_Convhidden: 8, n_Convlayers: 1, n_stride: 2, dropout: 0.2}

###### VSRTP2 ######
# 700K params
VSRTP2_1: {embed_dim: 8, n_heads: 4, n_transformerhidden: 256, n_transformerlayers: 6, n_Convhidden: 8, n_Convlayers: 1, n_stride: 2, dropout: 0.2}

###### VSRTP3 ######
# 700K params
VSRTP3_1: {embed_dim: 8, n_heads: 4, n_transformerhidden: 128, n_transformerlayers: 4, n_Convhidden: 20, n_Convlayers: 3, n_stride: 2, dropout: 0.2}

###### VSRTP4 ######
# 700K params
VSRTP4_1: {embed_dim: 8, n_heads: 4, n_transformerhidden: 256, n_transformerlayers: 6, n_Convhidden: 32, n_Convlayers: 12, n_stride: 2, dropout: 0.2}

###### VSRSA1 ######
# Sample
VSRSA1_SAMPLE: {embed_dim: 4, n_esthidden: 4, n_estlayers: 4, n_Convhidden: 20, n_Convlayers: 2, n_stride: 2, dropout: 0.5}

# 2.6 M Params
VSRSA1_1: {embed_dim: 128, n_esthidden: 128, n_estlayers: 2, n_Convhidden: 128, n_Convlayers: 8, n_stride: 2, dropout: 0.2}

###### VSRCNN1 ######

# 42.1 K Params
VSRCNN1_1: {n_hidden: 32, n_layers: 4}

#### OTHER ####

VSRRULA1_1: {n_transform_layers: 8, n_channels: 3, exp_channels: 8, bottle_neck_exp_channels: 8, n_layers: 8, scale_factor: 4}

VSRRUCV1_1: {n_transform_layers: 10, n_channels: 3, exp_channels: 16, bottle_neck_exp_channels: 16, n_layers: 8, scale_factor: 4}

VSRRULA1_2: {n_transform_layers: 4, n_channels: 3, exp_channels: 10, bottle_neck_exp_channels: 10, n_layers: 4, scale_factor: 4}

VSRRUCV1_2: {n_transform_layers: 4, n_channels: 3, exp_channels: 20, bottle_neck_exp_channels: 20, n_layers: 4, scale_factor: 4}